project "MonoMac_parse" -- parse.exe
    category "Mac"
    kind "ConsoleApp"
    language "C#"

    compilefiles {
        "parse.cs",
    }

done "MonoMac_parse"


-- build the monomac code generator and in postbuild action generates the
-- sources.
--
project "MonoMac_bmac" -- bmac.exe
    category "Mac"
    kind "ConsoleApp"
    language "C#"

    flags "Unsafe"

    defines {
        "NET_4_0",
        "GENERATOR",
        "MONOMAC",
        "MONOMAC_BOOTSTRAP",
    }

    compilefiles {
	"../../maccore/src/generator.cs",
	"../../maccore/src/Options.cs",
	"../../maccore/src/btouch.cs",
    }

    linkprojects {
        "MonoMac_Core",
    }

    postbuildactions { program = "./generate_sources.sh", args = "" }

done "MonoMac_bmac"


project "MonoMac_Core" -- core.dll
    category "Mac"
    kind "SharedLib"
    language "C#"

    flags "Unsafe"

    defines {
        "NET_4_0",
        "GENERATOR",
        "MONOMAC",
        "MONOMAC_BOOTSTRAP",
        "COREBUILD",
    }

    compilefiles {
        --
        -- from monomac/src/Makefile CORE_SOURCES:
        --
	"Constants.cs",
	"AppKit/Enums.cs",
	"CoreImage/Enums.cs",
	"Foundation/EnumDesktop.cs",
	"Foundation/NSObject.cs",
	"ObjCRuntime/Class.cs",
	"ObjCRuntime/Messaging.cs",
	"ObjCRuntime/NativeConstructorBuilder.cs",
	"ObjCRuntime/NativeImplementationBuilder.cs",
	"ObjCRuntime/NativeMethodBuilder.cs",
	"ObjCRuntime/MethodDescription.cs",
	"ObjCRuntime/NSObjectMarshaler.cs",
	"ObjCRuntime/SelectorMarshaler.cs",
	"ObjCRuntime/Runtime.cs",
	"ObjCRuntime/RequiredFrameworkAttribute.cs",
	"ObjCRuntime/Selector.cs",
	"QTKit/Defs.cs",
	"QTKit/Enums.cs",
	"OpenGL/CGLEnums.cs",
	"OpenGL/CGLContext.cs",
	"OpenGL/CGLPixelFormat.cs",
        -- "PdfKit/Enums.cs,"
        -- "WebKit/Enums.cs,"

        --
        -- from monomac/src/Make.shared SHARED_CORE_SOURCE
        --
        "../../maccore/src/CoreAnimation/CATransform3D.cs",
        "../../maccore/src/CoreAnimation/CAEnums.cs",
        "../../maccore/src/CoreFoundation/CFString.cs",
        "../../maccore/src/CoreFoundation/CFUrl.cs",
        "../../maccore/src/CoreFoundation/CFRunLoop.cs",
        "../../maccore/src/CoreFoundation/Dispatch.cs",
        "../../maccore/src/CoreGraphics/CGAffineTransform.cs",
        "../../maccore/src/CoreGraphics/CGBitmapContext.cs",
        "../../maccore/src/CoreGraphics/CGColor.cs",
        "../../maccore/src/CoreGraphics/CGColorSpace.cs",
        "../../maccore/src/CoreGraphics/CGContext.cs",
        "../../maccore/src/CoreGraphics/CGDataProvider.cs",
        "../../maccore/src/CoreGraphics/CGFont.cs",
        "../../maccore/src/CoreGraphics/CGGeometry.cs",
        "../../maccore/src/CoreGraphics/CGGradient.cs",
        "../../maccore/src/CoreGraphics/CGImage.cs",
        "../../maccore/src/CoreGraphics/CGLayer.cs",
        "../../maccore/src/CoreGraphics/CGPDFDocument.cs",
        "../../maccore/src/CoreGraphics/CGPDFPage-2.cs",
        "../../maccore/src/CoreGraphics/CGPDFPage.cs",
        "../../maccore/src/CoreGraphics/CGPath.cs",
        "../../maccore/src/CoreGraphics/CGPattern.cs",
        "../../maccore/src/CoreMedia/CMBlockBuffer.cs",
        "../../maccore/src/CoreMedia/CMFormatDescription.cs",
        "../../maccore/src/CoreMedia/CMSampleBuffer.cs",
        "../../maccore/src/CoreMedia/CoreMedia.cs",
        "../../maccore/src/CoreVideo/CVBuffer.cs",
        "../../maccore/src/CoreVideo/CVImageBuffer.cs",
        "../../maccore/src/CoreVideo/CVTime.cs",
        "../../maccore/src/CoreVideo/CoreVideo.cs",
        "../../maccore/src/CoreVideo/CVPixelBuffer.cs",
        "../../maccore/src/CoreVideo/CVPixelBufferPool.cs",
        "../../maccore/src/CoreVideo/CVPixelFormatDescription.cs",
        "../../maccore/src/Foundation/ConnectAttribute.cs",
        "../../maccore/src/Foundation/Enum.cs",
        "../../maccore/src/Foundation/ExportAttribute.cs",
        "../../maccore/src/Foundation/ModelAttribute.cs",
        "../../maccore/src/Foundation/NSAction.cs",
        "../../maccore/src/Foundation/NSDecimal.cs",
        "../../maccore/src/Foundation/NSRange.cs",
        "../../maccore/src/Foundation/NSString.cs",
        "../../maccore/src/Foundation/RegisterAttribute.cs",
        "../../maccore/src/Foundation/PreserveAttribute.cs",
        "../../maccore/src/ObjCRuntime/ArgumentSemantic.cs",
        "../../maccore/src/ObjCRuntime/AlphaAttribute.cs",
        "../../maccore/src/ObjCRuntime/Blocks.cs",
        "../../maccore/src/ObjCRuntime/Dlfcn.cs",
        "../../maccore/src/ObjCRuntime/NSStringMarshal.cs",
        "../../maccore/src/ObjCRuntime/INativeObject.cs",
        "../../maccore/src/ObjCRuntime/SinceAttribute.cs",
        "../../maccore/src/ObjCRuntime/TypeConverter.cs",
        "../../maccore/src/MonoPInvokeCallbackAttribute.cs",
        -- "../../maccore/src/CoreLocation/CLEnums.cs",
        "../../maccore/src/CoreLocation/CoreLocation.cs",
        "../../maccore/src/CoreData/Enums.cs",
    }

    linksystemlibs {
        "System",
        "System.Drawing",
    }

done "MonoMac_Core"


project "MonoMac" -- monomac.dll
    category "Mac"
    kind "SharedLib"
    language "C#"
    flags "Unsafe"
    strongkeyfile "../../../Sooloos.snk"

    defines {
        "OBJECT_REF_TRACKING",
        "MONOMAC",
    }

    compilefiles {
        --
        -- from monomac/src/Makefile CORE_SOURCES:
        --
	"Constants.cs",
	"AppKit/Enums.cs",
	"CoreImage/Enums.cs",
	"Foundation/EnumDesktop.cs",
	"Foundation/NSObject.cs",
	"ObjCRuntime/Class.cs",
	"ObjCRuntime/Messaging.cs",
	"ObjCRuntime/NativeConstructorBuilder.cs",
	"ObjCRuntime/NativeImplementationBuilder.cs",
	"ObjCRuntime/NativeMethodBuilder.cs",
	"ObjCRuntime/MethodDescription.cs",
	"ObjCRuntime/NSObjectMarshaler.cs",
	"ObjCRuntime/SelectorMarshaler.cs",
	"ObjCRuntime/Runtime.cs",
	"ObjCRuntime/RequiredFrameworkAttribute.cs",
	"ObjCRuntime/Selector.cs",
	"QTKit/Defs.cs",
	"QTKit/Enums.cs",
	"OpenGL/CGLEnums.cs",
	"OpenGL/CGLContext.cs",
	"OpenGL/CGLPixelFormat.cs",
        -- "PdfKit/Enums.cs,"
        -- "WebKit/Enums.cs,"

        --
        -- from monomac/src/Makefile MONOMAC_SOURCES:
        --
        "Foundation/NSObjectMac.cs",
        "Foundation/NSSearchPath.cs",
        "AppKit/ActionDispatcher.cs",
        "AppKit/Functions.cs",
        "AppKit/NSApplication.cs",
        "AppKit/NSApplicationDelegate.cs",
        "AppKit/NSBitmapImageRep.cs",
        "AppKit/NSButton.cs",
        "AppKit/NSColor.cs",
        "AppKit/NSControl.cs",
        "AppKit/NSGraphics.cs",
        "AppKit/NSImage.cs",
        "AppKit/NSLevelIndicator.cs",
        "AppKit/NSMatrix.cs",
        "AppKit/NSMenu.cs",
        "AppKit/NSMenuItem.cs",
        "AppKit/NSOpenGLPixelFormat.cs",
        "AppKit/NSWindow.cs",
        "Growl/Constants.cs",
        -- "AppKit/NSTableView.cs",
        -- "AppKit/NSBezierPath.cs",
        -- "AppKit/NSGradient.cs",
        -- "AppKit/NSLevelIndicator.cs",
        -- "AppKit/NSMatrix.cs",
        -- "AppKit/NSActionCell.cs",
        -- "AppKit/BeginSheet.cs",
        -- "AppKit/DoubleWrapper.cs",
        -- "AppKit/NSPopUpButton.cs",
        -- "AppKit/NSPopUpButtonCell.cs",
        -- "AppKit/NSSegmentedControl.cs",
        -- "CoreImage/CIContext.cs",
        -- "CoreImage/CISampler.cs",
        -- "CoreImage/CIVector.cs",
        -- "CoreVideo/CVDisplayLink.cs",
        -- "QTKit/QTCaptureDevice.cs",
        -- "QTKit/QTMovie.cs",
        -- "WebKit/DomNode.cs",
        -- "WebKit/Enumerators.cs",
        -- "WebKit/Indexers.cs",
        -- "WebKit/WebKit.cs",
        -- "WebKit/WebView.cs",
        -- "OpenGL/FrameEventArgs.cs",
        -- "OpenGL/IGameWindow.cs",
        -- "OpenGL/INativeWindow.cs",
        -- "OpenGL/WindowBorder.cs",
        -- "OpenGL/WindowState.cs",
        -- "OpenGL/MonoMacGameView.cs",

        --
        -- from monomac/src/Make.shared SHARED_SOURCE
        --
        "../../maccore/src/AudioToolbox/AudioBufferList.cs",
        "../../maccore/src/AudioToolbox/AudioFile.cs",
        "../../maccore/src/AudioToolbox/AudioFileStream.cs",
        "../../maccore/src/AudioToolbox/AudioQueue.cs",
        "../../maccore/src/AudioToolbox/AudioServices.cs",
        "../../maccore/src/AudioToolbox/AudioSession.cs",
        "../../maccore/src/AudioToolbox/AudioSessions.cs",
        "../../maccore/src/AudioToolbox/AudioType.cs",
        "../../maccore/src/AudioToolbox/SystemSound.cs",
        "../../maccore/src/AudioUnit/AUGraph.cs",
        "../../maccore/src/AudioUnit/AudioComponent.cs",
        "../../maccore/src/AudioUnit/AudioComponentDescription.cs",
        "../../maccore/src/AudioUnit/AudioGraphEventArgs.cs",
        "../../maccore/src/AudioUnit/AudioUnit.cs",
        "../../maccore/src/AudioUnit/AudioUnitEventArgs.cs",
        "../../maccore/src/AudioUnit/AudioUnitUtils.cs",
        "../../maccore/src/AudioUnit/ExtAudioFile.cs",
        "../../maccore/src/AudioUnit/_AudioConverter.cs",
        "../../maccore/src/AudioUnit/_AudioConverterEventArgs.cs",
        "../../maccore/src/CoreFoundation/CFArray.cs",
        "../../maccore/src/CoreFoundation/CFBoolean.cs",
        "../../maccore/src/CoreFoundation/CFDictionary.cs",
        "../../maccore/src/CoreFoundation/CFException.cs",
        "../../maccore/src/CoreFoundation/CFType.cs",
        "../../maccore/src/CoreGraphics/CGContextPDF.cs",
        "../../maccore/src/CoreGraphics/CGDataProvider-2.cs",
        "../../maccore/src/CoreGraphics/CGFunction.cs",
        "../../maccore/src/CoreGraphics/CGPDFArray.cs",
        "../../maccore/src/CoreGraphics/CGPDFStream.cs",
        "../../maccore/src/CoreGraphics/CGPDFDictionary.cs",
        "../../maccore/src/CoreGraphics/CGShading.cs",
        "../../maccore/src/CoreText/Adapter.cs",
        "../../maccore/src/CoreText/CTFont.Generator.cs",
        "../../maccore/src/CoreText/CTFont.cs",
        "../../maccore/src/CoreText/CTFontCollection.cs",
        "../../maccore/src/CoreText/CTFontDescriptor.cs",
        "../../maccore/src/CoreText/CTFontManager.cs",
        "../../maccore/src/CoreText/CTFontNameKey.cs",
        "../../maccore/src/CoreText/CTFontTrait.cs",
        "../../maccore/src/CoreText/CTFrame.cs",
        "../../maccore/src/CoreText/CTFramesetter.cs",
        "../../maccore/src/CoreText/CTGlyphInfo.cs",
        "../../maccore/src/CoreText/CTLine.cs",
        "../../maccore/src/CoreText/CTParagraphStyle.cs",
        "../../maccore/src/CoreText/CTRun.cs",
        "../../maccore/src/CoreText/CTRunDelegate.cs",
        "../../maccore/src/CoreText/CTStringAttributes.cs",
        "../../maccore/src/CoreText/CTTextTab.cs",
        "../../maccore/src/CoreText/CTTypesetter.cs",
        "../../maccore/src/CoreText/ConstructorError.cs",
        "../../maccore/src/Foundation/ModelNotImplementedException.cs",
        "../../maccore/src/Foundation/NSAutoreleasePool.cs",
        "../../maccore/src/Foundation/NSArray.cs",
        "../../maccore/src/Foundation/NSBundle.cs",
        "../../maccore/src/Foundation/NSCoder.cs",
        "../../maccore/src/Foundation/NSData.cs",
        "../../maccore/src/Foundation/NSDate.cs",
        "../../maccore/src/Foundation/NSDictionary.cs",
        "../../maccore/src/Foundation/NSError.cs",
        "../../maccore/src/Foundation/NSFileManager.cs",
        "../../maccore/src/Foundation/NSHttpCookie.cs",
        "../../maccore/src/Foundation/NSHttpCookieStorage.cs",
        "../../maccore/src/Foundation/NSIndexPath.cs",
        "../../maccore/src/Foundation/NSIndexSet.cs",
        "../../maccore/src/Foundation/NSInputStream.cs",
        "../../maccore/src/Foundation/NSKeyedArchiver.cs",
        "../../maccore/src/Foundation/NSKeyedUnarchiver.cs",
        "../../maccore/src/Foundation/NSMutableAttributedString.cs",
        "../../maccore/src/Foundation/NSMutableData.cs",
        "../../maccore/src/Foundation/NSMutableDictionary.cs",
        "../../maccore/src/Foundation/NSMutableUrlRequest.cs",
        "../../maccore/src/Foundation/NSNotificationCenter.cs",
        "../../maccore/src/Foundation/NSNumber.cs",
        "../../maccore/src/Foundation/NSNumber2.cs",
        "../../maccore/src/Foundation/NSObject2.cs",
        "../../maccore/src/Foundation/NSOutputStream.cs",
        "../../maccore/src/Foundation/NSRunLoop.cs",
        "../../maccore/src/Foundation/NSSet.cs",
        "../../maccore/src/Foundation/NSString2.cs",
        "../../maccore/src/Foundation/NSTimer.cs",
        "../../maccore/src/Foundation/NSUrl.cs",
        "../../maccore/src/Foundation/NSUrlConnection.cs",
        "../../maccore/src/Foundation/NSUserDefaults.cs",
        "../../maccore/src/Foundation/NSValue.cs",
        "../../maccore/src/Foundation/ToString.cs",
        "../../maccore/src/ImageIO/CGImageSource.cs",
        "../../maccore/src/ImageIO/CGImageDestination.cs",
        "../../maccore/src/ObjCRuntime/CompileFlagsAttribute.cs",
        -- "../../maccore/src/Security/Enums.cs",
        -- "../../maccore/src/Security/Certificate.cs",
        -- "../../maccore/src/Security/Items.cs",
        -- "../../maccore/src/Security/Policy.cs",
        -- "../../maccore/src/Security/Trust.cs",
        -- "../../maccore/src/AddressBook/ABAddressBook.cs",
        -- "../../maccore/src/AddressBook/ABGroup.cs",
        -- "../../maccore/src/AddressBook/ABMultiValue.cs",
        -- "../../maccore/src/AddressBook/ABPerson.cs",
        -- "../../maccore/src/AddressBook/ABRecord.cs",
        -- "../../maccore/src/CoreAnimation/CADefs.cs",
        -- "../../maccore/src/CoreAnimation/CALayer.cs",
        -- "../../maccore/src/CoreAnimation/CATextLayer.cs",
        -- "../../maccore/src/CoreLocation/CoreLocation2.cs",
        -- "../../maccore/src/CoreLocation/CLLocationManager.cs",

        --
        -- from monomac/src/Make.shared SHARED_CORE_SOURCE
        --
        "../../maccore/src/CoreAnimation/CATransform3D.cs",
        "../../maccore/src/CoreAnimation/CAEnums.cs",
        "../../maccore/src/CoreFoundation/CFString.cs",
        "../../maccore/src/CoreFoundation/CFUrl.cs",
        "../../maccore/src/CoreFoundation/CFRunLoop.cs",
        "../../maccore/src/CoreFoundation/Dispatch.cs",
        "../../maccore/src/CoreGraphics/CGAffineTransform.cs",
        "../../maccore/src/CoreGraphics/CGBitmapContext.cs",
        "../../maccore/src/CoreGraphics/CGColor.cs",
        "../../maccore/src/CoreGraphics/CGColorSpace.cs",
        "../../maccore/src/CoreGraphics/CGContext.cs",
        "../../maccore/src/CoreGraphics/CGDataProvider.cs",
        "../../maccore/src/CoreGraphics/CGFont.cs",
        "../../maccore/src/CoreGraphics/CGGeometry.cs",
        "../../maccore/src/CoreGraphics/CGGradient.cs",
        "../../maccore/src/CoreGraphics/CGImage.cs",
        "../../maccore/src/CoreGraphics/CGLayer.cs",
        "../../maccore/src/CoreGraphics/CGPDFDocument.cs",
        "../../maccore/src/CoreGraphics/CGPDFPage-2.cs",
        "../../maccore/src/CoreGraphics/CGPDFPage.cs",
        "../../maccore/src/CoreGraphics/CGPath.cs",
        "../../maccore/src/CoreGraphics/CGPattern.cs",
        "../../maccore/src/CoreMedia/CMBlockBuffer.cs",
        "../../maccore/src/CoreMedia/CMFormatDescription.cs",
        "../../maccore/src/CoreMedia/CMSampleBuffer.cs",
        "../../maccore/src/CoreMedia/CoreMedia.cs",
        "../../maccore/src/CoreVideo/CVBuffer.cs",
        "../../maccore/src/CoreVideo/CVImageBuffer.cs",
        "../../maccore/src/CoreVideo/CVTime.cs",
        "../../maccore/src/CoreVideo/CoreVideo.cs",
        "../../maccore/src/CoreVideo/CVPixelBuffer.cs",
        "../../maccore/src/CoreVideo/CVPixelBufferPool.cs",
        "../../maccore/src/CoreVideo/CVPixelFormatDescription.cs",
        "../../maccore/src/Foundation/ConnectAttribute.cs",
        "../../maccore/src/Foundation/Enum.cs",
        "../../maccore/src/Foundation/ExportAttribute.cs",
        "../../maccore/src/Foundation/ModelAttribute.cs",
        "../../maccore/src/Foundation/NSAction.cs",
        "../../maccore/src/Foundation/NSDecimal.cs",
        "../../maccore/src/Foundation/NSRange.cs",
        "../../maccore/src/Foundation/NSString.cs",
        "../../maccore/src/Foundation/RegisterAttribute.cs",
        "../../maccore/src/Foundation/PreserveAttribute.cs",
        "../../maccore/src/ObjCRuntime/ArgumentSemantic.cs",
        "../../maccore/src/ObjCRuntime/AlphaAttribute.cs",
        "../../maccore/src/ObjCRuntime/Blocks.cs",
        "../../maccore/src/ObjCRuntime/Dlfcn.cs",
        "../../maccore/src/ObjCRuntime/NSStringMarshal.cs",
        "../../maccore/src/ObjCRuntime/INativeObject.cs",
        "../../maccore/src/ObjCRuntime/SinceAttribute.cs",
        "../../maccore/src/ObjCRuntime/TypeConverter.cs",
        "../../maccore/src/MonoPInvokeCallbackAttribute.cs",
        -- "../../maccore/src/CoreLocation/CLEnums.cs",
        -- "../../maccore/src/CoreLocation/CoreLocation.cs",
        -- "../../maccore/src/CoreData/Enums.cs",

        --
        -- from monomac/src/Makefile OPENTK_SOURCES:
        --
        -- "OpenGL/OpenTK/Graphics/Color4.cs",
        -- "OpenGL/OpenTK/Graphics/OpenGL/GL.cs",
        -- "OpenGL/OpenTK/Graphics/OpenGL/GLCore.cs",
        -- "OpenGL/OpenTK/Graphics/OpenGL/GLEnums.cs",
        -- "OpenGL/OpenTK/Graphics/OpenGL/GLHelper.cs",
        -- "OpenGL/OpenTK/Math/Half.cs",
        -- "OpenGL/OpenTK/Math/MathHelper.cs",
        -- "OpenGL/OpenTK/Math/Matrix3d.cs",
        -- "OpenGL/OpenTK/Math/Matrix4.cs",
        -- "OpenGL/OpenTK/Math/Matrix4d.cs",
        -- "OpenGL/OpenTK/Math/Quaternion.cs",
        -- "OpenGL/OpenTK/Math/Quaterniond.cs",
        -- "OpenGL/OpenTK/Math/Vector2.cs",
        -- "OpenGL/OpenTK/Math/Vector2d.cs",
        -- "OpenGL/OpenTK/Math/Vector2h.cs",
        -- "OpenGL/OpenTK/Math/Vector3.cs",
        -- "OpenGL/OpenTK/Math/Vector3d.cs",
        -- "OpenGL/OpenTK/Math/Vector3h.cs",
        -- "OpenGL/OpenTK/Math/Vector4.cs",
        -- "OpenGL/OpenTK/Math/Vector4d.cs",
        -- "OpenGL/OpenTK/Math/Vector4h.cs",

        --
        -- from "generated_source_list":
        -- TODO: instead of maintaining this list manually, read it from "generated_source_list" file
        --
        "ObjCRuntime/Messaging.g.cs",
        "AppKit/NSActionCell.g.cs",
        "AppKit/NSAnimation.g.cs",
        "AppKit/NSAnimationDelegate.g.cs",
        "AppKit/NSAnimationContext.g.cs",
        "AppKit/NSAlert.g.cs",
        "AppKit/NSAlertDelegate.g.cs",
        "AppKit/NSApplication.g.cs",
        "AppKit/NSApplicationDelegate.g.cs",
        "AppKit/NSArrayController.g.cs",
        "AppKit/NSBezierPath.g.cs",
        "AppKit/NSBitmapImageRep.g.cs",
        "AppKit/NSBox.g.cs",
        "AppKit/NSBrowser.g.cs",
        "AppKit/NSBrowserDelegate.g.cs",
        "AppKit/NSBrowserCell.g.cs",
        "AppKit/NSButtonCell.g.cs",
        "AppKit/NSButton.g.cs",
        "AppKit/NSCachedImageRep.g.cs",
        "AppKit/NSCell.g.cs",
        "AppKit/NSCIImageRep.g.cs",
        "AppKit/NSClipView.g.cs",
        "AppKit/NSCollectionViewItem.g.cs",
        "AppKit/NSCollectionView.g.cs",
        "AppKit/NSCollectionViewDelegate.g.cs",
        "AppKit/NSColor.g.cs",
        "AppKit/NSColorList.g.cs",
        "AppKit/NSColorPanel.g.cs",
        "AppKit/NSColorPicker.g.cs",
        "AppKit/NSColorSpace.g.cs",
        "AppKit/NSColorWell.g.cs",
        "AppKit/NSComboBox.g.cs",
        "AppKit/NSComboBoxDataSource.g.cs",
        "AppKit/NSControl.g.cs",
        "AppKit/NSController.g.cs",
        "AppKit/NSCursor.g.cs",
        "AppKit/NSCustomImageRep.g.cs",
        "AppKit/NSDatePicker.g.cs",
        "AppKit/NSDatePickerCell.g.cs",
        "AppKit/NSDatePickerCellDelegate.g.cs",
        "AppKit/NSDockTile.g.cs",
        "AppKit/NSDockTilePlugIn.g.cs",
        "AppKit/NSDocument.g.cs",
        "AppKit/NSDocumentController.g.cs",
        "AppKit/NSDraggingInfo.g.cs",
        "AppKit/NSDraggingDestination.g.cs",
        "AppKit/NSDraggingSource.g.cs",
        "AppKit/NSDrawer.g.cs",
        "AppKit/NSDrawerDelegate.g.cs",
        "AppKit/NSFileWrapper.g.cs",
        "AppKit/NSFont.g.cs",
        "AppKit/NSFontDescriptor.g.cs",
        "AppKit/NSFontManager.g.cs",
        "AppKit/NSFontPanel.g.cs",
        "AppKit/NSForm.g.cs",
        "AppKit/NSFormCell.g.cs",
        "AppKit/NSGlyphGenerator.g.cs",
        "AppKit/NSGradient.g.cs",
        "AppKit/NSGraphicsContext.g.cs",
        "AppKit/NSEPSImageRep.g.cs",
        "AppKit/NSEvent.g.cs",
        "AppKit/NSMenu.g.cs",
        "AppKit/NSMenuDelegate.g.cs",
        "AppKit/NSMenuItem.g.cs",
        "AppKit/NSMenuItemCell.g.cs",
        "AppKit/NSMenuView.g.cs",
        "AppKit/NSNib.g.cs",
        "AppKit/NSObjectController.g.cs",
        "AppKit/NSOpenGLPixelFormat.g.cs",
        "AppKit/NSOpenGLPixelBuffer.g.cs",
        "AppKit/NSOpenGLContext.g.cs",
        "AppKit/NSOpenGLView.g.cs",
        "AppKit/NSOpenPanel.g.cs",
        "AppKit/NSOpenSavePanelDelegate.g.cs",
        "AppKit/NSOutlineView.g.cs",
        "AppKit/NSOutlineViewDelegate.g.cs",
        "AppKit/NSOutlineViewDataSource.g.cs",
        "AppKit/NSHelpManager.g.cs",
        "AppKit/NSImage.g.cs",
        "AppKit/NSImageDelegate.g.cs",
        "AppKit/NSImageCell.g.cs",
        "AppKit/NSImageRep.g.cs",
        "AppKit/NSImageView.g.cs",
        "AppKit/NSMatrix.g.cs",
        "AppKit/NSLevelIndicator.g.cs",
        "AppKit/NSLevelIndicatorCell.g.cs",
        "AppKit/NSLayoutManager.g.cs",
        "AppKit/NSLayoutManagerDelegate.g.cs",
        "AppKit/NSMatrixDelegate.g.cs",
        "AppKit/NSPageLayout.g.cs",
        "AppKit/NSPanel.g.cs",
        "AppKit/NSParagraphStyle.g.cs",
        "AppKit/NSMutableParagraphStyle.g.cs",
        "AppKit/NSPasteboard.g.cs",
        "AppKit/NSPasteboardWriting.g.cs",
        "AppKit/NSPasteboardItem.g.cs",
        "AppKit/NSPasteboardItemDataProvider.g.cs",
        "AppKit/NSPasteboardReading.g.cs",
        "AppKit/NSPathCell.g.cs",
        "AppKit/NSPathCellDelegate.g.cs",
        "AppKit/NSPathComponentCell.g.cs",
        "AppKit/NSPathControl.g.cs",
        "AppKit/NSPathControlDelegate.g.cs",
        "AppKit/NSPopUpButton.g.cs",
        "AppKit/NSPopUpButtonCell.g.cs",
        "AppKit/NSPrinter.g.cs",
        "AppKit/NSPrintInfo.g.cs",
        "AppKit/NSPrintOperation.g.cs",
        "AppKit/NSPrintPanelAccessorizing.g.cs",
        "AppKit/NSPrintPanel.g.cs",
        "AppKit/NSProgressIndicator.g.cs",
        "AppKit/NSResponder.g.cs",
        "AppKit/NSRulerMarker.g.cs",
        "AppKit/NSRulerView.g.cs",
        "AppKit/NSSavePanel.g.cs",
        "AppKit/NSScreen.g.cs",
        "AppKit/NSScroller.g.cs",
        "AppKit/NSScrollView.g.cs",
        "AppKit/NSSearchField.g.cs",
        "AppKit/NSSearchFieldCell.g.cs",
        "AppKit/NSSegmentedControl.g.cs",
        "AppKit/NSSegmentedCell.g.cs",
        "AppKit/NSSlider.g.cs",
        "AppKit/NSSliderCell.g.cs",
        "AppKit/NSSpeechRecognizer.g.cs",
        "AppKit/NSSpeechRecognizerDelegate.g.cs",
        "AppKit/NSSpeechSynthesizer.g.cs",
        "AppKit/NSSpeechSynthesizerDelegate.g.cs",
        "AppKit/NSSpellChecker.g.cs",
        "AppKit/NSSound.g.cs",
        "AppKit/NSSoundDelegate.g.cs",
        "AppKit/NSSplitView.g.cs",
        "AppKit/NSSplitViewDelegate.g.cs",
        "AppKit/NSStatusBar.g.cs",
        "AppKit/NSStatusItem.g.cs",
        "AppKit/NSShadow.g.cs",
        "AppKit/NSView.g.cs",
        "AppKit/NSViewAnimation.g.cs",
        "AppKit/NSViewController.g.cs",
        "AppKit/NSTableColumn.g.cs",
        "AppKit/NSTableView.g.cs",
        "AppKit/NSTableViewDelegate.g.cs",
        "AppKit/NSTableViewDataSource.g.cs",
        "AppKit/NSTableViewSource.g.cs",
        "AppKit/NSTableHeaderCell.g.cs",
        "AppKit/NSTableHeaderView.g.cs",
        "AppKit/NSTabView.g.cs",
        "AppKit/NSTabViewDelegate.g.cs",
        "AppKit/NSTabViewItem.g.cs",
        "AppKit/NSText.g.cs",
        "AppKit/NSTextDelegate.g.cs",
        "AppKit/NSTextAttachmentCell.g.cs",
        "AppKit/NSTextAttachment.g.cs",
        "AppKit/NSTextBlock.g.cs",
        "AppKit/NSTextField.g.cs",
        "AppKit/NSSecureTextField.g.cs",
        "AppKit/NSTextFieldDelegate.g.cs",
        "AppKit/NSTextFieldCell.g.cs",
        "AppKit/NSSecureTextFieldCell.g.cs",
        "AppKit/NSTextInputContext.g.cs",
        "AppKit/NSTextList.g.cs",
        "AppKit/NSTextTableBlock.g.cs",
        "AppKit/NSTextTable.g.cs",
        "AppKit/NSTextContainer.g.cs",
        "AppKit/NSTextStorage.g.cs",
        "AppKit/NSTextStorageDelegate.g.cs",
        "AppKit/NSTextTab.g.cs",
        "AppKit/NSTextView.g.cs",
        "AppKit/NSTextViewDelegate.g.cs",
        "AppKit/NSTokenField.g.cs",
        "AppKit/NSTokenFieldDelegate.g.cs",
        "AppKit/NSToolbar.g.cs",
        "AppKit/NSToolbarDelegate.g.cs",
        "AppKit/NSToolbarItem.g.cs",
        "AppKit/NSTouch.g.cs",
        "AppKit/NSTrackingArea.g.cs",
        "AppKit/NSTreeNode.g.cs",
        "AppKit/NSTreeController.g.cs",
        "AppKit/NSTypesetter.g.cs",
        "AppKit/NSWindow.g.cs",
        "AppKit/NSWindowController.g.cs",
        "AppKit/NSWindowDelegate.g.cs",
        "AppKit/NSWorkspace.g.cs",
        "AppKit/NSRunningApplication.g.cs",
        "AppKit/NSStepper.g.cs",
        "AppKit/NSPredicateEditorRowTemplate.g.cs",
        "AppKit/NSRuleEditor.g.cs",
        "AppKit/NSRuleEditorDelegate.g.cs",
        "AppKit/NSPredicateEditor.g.cs",
        "CoreImage/CIColor.g.cs",
        "CoreImage/CIContext.g.cs",
        "CoreImage/CIFilter.g.cs",
        "CoreImage/CIFilterGenerator.g.cs",
        "CoreImage/CIFilterShape.g.cs",
        "CoreImage/CIImage.g.cs",
        "CoreImage/CIImageAccumulator.g.cs",
        "CoreImage/CIKernel.g.cs",
        "CoreImage/CIPlugIn.g.cs",
        "CoreImage/CISampler.g.cs",
        "CoreImage/CIVector.g.cs",
        "Foundation/NSAffineTransform.g.cs",
        "Foundation/NSMutableCharacterSet.g.cs",
        "Foundation/NSOrthography.g.cs",
        "Foundation/NSTextCheckingResult.g.cs",
        "Foundation/NSTask.g.cs",
        "Foundation/NSAppleEventDescriptor.g.cs",
        "Growl/GrowlApplicationBridge.g.cs",
        "Growl/GrowlDelegate.g.cs",
        "Foundation/NSArray.g.cs",
        "Foundation/NSAttributedString.g.cs",
        "Foundation/NSCache.g.cs",
        "Foundation/NSCacheDelegate.g.cs",
        "Foundation/NSCachedUrlResponse.g.cs",
        "Foundation/NSCalendar.g.cs",
        "Foundation/NSCharacterSet.g.cs",
        "Foundation/NSCoder.g.cs",
        "Foundation/NSComparisonPredicate.g.cs",
        "Foundation/NSCompoundPredicate.g.cs",
        "Foundation/NSData.g.cs",
        "Foundation/NSDateComponents.g.cs",
        "Foundation/NSDateFormatter.g.cs",
        "Foundation/NSFormatter.g.cs",
        "Foundation/NSKeyedArchiverDelegate.g.cs",
        "Foundation/NSKeyedUnarchiverDelegate.g.cs",
        "Foundation/NSKeyedArchiver.g.cs",
        "Foundation/NSKeyedUnarchiver.g.cs",
        "Foundation/NSMetadataQuery.g.cs",
        "Foundation/NSMetadataQueryDelegate.g.cs",
        "Foundation/NSMetadataItem.g.cs",
        "Foundation/NSMetadataQueryAttributeValueTuple.g.cs",
        "Foundation/NSMetadataQueryResultGroup.g.cs",
        "Foundation/NSMutableAttributedString.g.cs",
        "Foundation/NSMutableData.g.cs",
        "Foundation/NSDate.g.cs",
        "Foundation/NSDictionary.g.cs",
        "Foundation/NSEnumerator.g.cs",
        "Foundation/NSError.g.cs",
        "Foundation/NSException.g.cs",
        "Foundation/NSExpression.g.cs",
        "Foundation/NSNull.g.cs",
        "Foundation/NSLocale.g.cs",
        "Foundation/NSRunLoop.g.cs",
        "Foundation/NSSet.g.cs",
        "Foundation/NSSortDescriptor.g.cs",
        "Foundation/NSTimer.g.cs",
        "Foundation/NSTimeZone.g.cs",
        "Foundation/NSUserDefaults.g.cs",
        "Foundation/NSUrl.g.cs",
        "Foundation/NSUrlCache.g.cs",
        "Foundation/NSUrlAuthenticationChallenge.g.cs",
        "Foundation/NSUrlConnection.g.cs",
        "Foundation/NSUrlConnectionDelegate.g.cs",
        "Foundation/NSUrlCredential.g.cs",
        "Foundation/NSUndoManager.g.cs",
        "Foundation/NSUrlProtectionSpace.g.cs",
        "Foundation/NSUrlRequest.g.cs",
        "Foundation/NSMutableDictionary.g.cs",
        "Foundation/NSMutableSet.g.cs",
        "Foundation/NSMutableUrlRequest.g.cs",
        "Foundation/NSUrlResponse.g.cs",
        "Foundation/NSStream.g.cs",
        "Foundation/NSStreamDelegate.g.cs",
        "Foundation/NSString.g.cs",
        "Foundation/NSInputStream.g.cs",
        "Foundation/NSObject.g.cs",
        "Foundation/NSOperation.g.cs",
        "Foundation/NSBlockOperation.g.cs",
        "Foundation/NSOperationQueue.g.cs",
        "Foundation/NSOutputStream.g.cs",
        "Foundation/NSHttpCookie.g.cs",
        "Foundation/NSHttpCookieStorage.g.cs",
        "Foundation/NSHttpUrlResponse.g.cs",
        "Foundation/NSBundle.g.cs",
        "Foundation/NSIndexPath.g.cs",
        "Foundation/NSIndexSet.g.cs",
        "Foundation/NSMutableIndexSet.g.cs",
        "Foundation/NSNetService.g.cs",
        "Foundation/NSNetServiceDelegate.g.cs",
        "Foundation/NSNetServiceBrowser.g.cs",
        "Foundation/NSNetServiceBrowserDelegate.g.cs",
        "Foundation/NSNotification.g.cs",
        "Foundation/NSNotificationCenter.g.cs",
        "Foundation/NSDistributedNotificationCenter.g.cs",
        "Foundation/NSNotificationQueue.g.cs",
        "Foundation/NSValue.g.cs",
        "Foundation/NSNumber.g.cs",
        "Foundation/NSNumberFormatter.g.cs",
        "Foundation/NSDecimalNumber.g.cs",
        "Foundation/NSThread.g.cs",
        "Foundation/NSProcessInfo.g.cs",
        "Foundation/NSPurgeableData.g.cs",
        "Foundation/NSFileManager.g.cs",
        "Foundation/NSFileManagerDelegate.g.cs",
        "Foundation/NSDirectoryEnumerator.g.cs",
        "Foundation/NSPredicate.g.cs",
        "Foundation/NSUrlDownload.g.cs",
        "Foundation/NSUrlDownloadDelegate.g.cs",
        "Foundation/NSUrlProtocolClient.g.cs",
        "Foundation/NSUrlProtocol.g.cs",
    }

    linksystemlibs {
        "System",
        "System.Drawing",
    }

    copyprojects {
        -- this should be a "dependprojects"
        "MonoMac_bmac"
    }

done "MonoMac"
